# n=int(input("Input a num: "))

# b = [[0 for item in range(n)] for element in range(n)]
# # print(b)

# row=0
# col=n//2
# b[row][col]=1
# for i in range(2,n*n+1):
#     row=row-1
#     col=col+1
#     if row<0 and col>n-1:
#         row=row+2
#         col=n-1
#     elif row<0:
#         row=n-1
#     elif col>n-1:
#         col=0
#     if b[row][col]!=0:
#         row=row+2
#         col=col-1
#     b[row][col]=i
# print(b)


# Ruppal 
# She is tapkara chattisgarh 
# She has completed graduation from BA
# Her father is a  business  and mother is homemaker
# Her aim is to have a stable job 
# Her hobbies are reading novels 
# strength : have her own strong opinions .
# weakness is to take time for any decision .
# Her friend told about navgurukul . 
# she wants to study in these technical courses .





# Reading : good in reading
# explaining : good in explanation .
# Speaking : she is able to speak in english .
# Understanding : able to understand 



# whole no. : wrong 
# smallest natural no. : her ans is 10 , what is natural no. : hr answer is that natural no. starts from 0 .
# odd no. , even no. : correct
# biggest odd no. : she forget about the biggest no. 
# biggest even no. : her answer is 100
# (a-b)^2: not getting the formula
# 6x-2+4x=7+3x : she adds all no. , with and without x , her answer is 22. 
# lcm and hcf 12 and 18 :she solves but incorrect she  don't know how to find lcm and solves it by doing division .
# 0.54/0.2: 


#________________________________________________________________________________________________________________


# Ruppal 
# She is from  chattisgarh 
# She has completed graduation from BA
# Her father is a  business  and mother is homemaker
# Her aim is to have a stable job 
# Her hobbies are reading novels 
# strength : have her own strong opinions .
# weakness is to take time for any decision .
# Her friend told about navgurukul . 
# she wants to study in these technical courses .





# Reading : good in reading
# explaining : good in explanation .
# Speaking : she is able to speak in english .
# Understanding : able to understand 




#------------------

# Shireen 
# She has completed 12 and now doing B.A  2nd year from ignou . 
# There are 6 members in her family .
# She has completed python and already  starts learning java .
# Her hobbies are talk to different peoples and interact with them for gaing information about culture .
# Her aim is to get a good job .
# Her father is living in lucknow , he is a carpenter  and her  mother is housewife .
# Her strength is her family.

# She is good in reading ,
# She triees  to explain and able to  explain well
# she is able to understand whatever I speak to her and  whatever she reads in english . 
# Her speaking skills is also good .


# math test :

# What is whole no. and  even no. : her answer for even no. is  incorrect , but her answer is correct for  whole no . 
# What is natural no. and prime  no. : she give right answer for prime no. , the no. who have 2 factors is a  prime no. , she don't know what is  natural no.
# which is the bigest  natural no. : her answer for this question is 999 , which is incorrect 
# 1 is a prime no.  or not : answer correct , she said 1 has only 1 factor so it is not prime .
# (a-b)^2: she said she didn't remember the formulas .
# 5x+3-8x=2+6 : answer wrong , her answer is 1/8 , solved it incorrect 
# x^2+2x=15: unable to solved correctly , she solved it but her method is incorrect .
# lcm and hcf of 12 and 16: she done lcm correct but hcf is incorrect . 

# She didn't know about basic algebra so she is fail in algebra interview.


#_______________________________________________________________
n=int(input())
b=1
l1=[]
if (n**2)//2!=0:
   while i<=n:
print(l1)
l2=[]
b=((n**2)//2)+1
for i in range(0,((n**2)//2)+1):
        l2.append(b)
        b+=1
print(l2)























